### ISSUE TITLE
Putting my own username and password for Drupal 8

### ISSUE THREAD

**Issue by AmineBena17** [contentacms/contenta_angular#107]
Hi,

I'm trying to put my own configuration for my drupal, i've already change the URl but i should fills my username and password to use the API's, what should i change in my configuration file ?

Kind Regards.

**Comment by joaogarin** [comment]
You mean for authentication? This repo currently doesn't do anything that requires authentication so for that purpose you shoudn't have to do anything unless you need to provide authentication / authorization. for that I would recommend going through the simple auth videos : https://www.youtube.com/watch?v=rTcC0maPLSA&list=PLZOQ_ZMpYrZtqy5-o7KoDhM3n6M0duBjX

And also join the chat in the drupal slack channel, you might get some further help there https://drupal.slack.com/messages/C5A70F7D1

**Comment by AmineBena17** [comment]
thank you for the help

@joaogarin is it possible to invite me in drupal slack channel please ? my email is : l_a-berlingo@live.fr
