### ISSUE TITLE
Add a pager

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_angular#17]
Let's add a pager to our front page recipes listing, after #16 gets in. This will require a modification to the JSON API Extras configuration on the public API site if we want to be able to provide the appropriate contextual information to our pager, like total record count and page number.

**Comment by joaogarin** [comment]
This is a good flexible pagination package for angular apps https://github.com/michaelbromley/ngx-pagination

**Comment by mrjmd** [comment]
Does our "limit" filter satisfy this requirement for now? Or would we want both?

**Comment by joaogarin** [comment]
I think for now we can stay like this. lets add this in a later step maybe?

**Comment by mrjmd** [comment]
After some UX discussion with the team I recommend we close this issue out and instead move towards a lower default and infinite scroll  #50.

Closing this, if there's a strong concern about this switch in direction feel free to re-open this for further discussion.
