### ISSUE TITLE
Add codecov support

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_angular#26]
In the interest of tracking and encouraging improvement in our code coverage, let's integrate with [Codecov](https://codecov.io/gh).

I've never set this up before, but have done a little research. I've gone ahead and connected this repo with Codecov, but it looks like there are [several more steps](http://blog.fossasia.org/linking-codecov-to-your-angular2-project/) to integration and having an accurate badge on our repo's README.

**Comment by joaogarin** [comment]
I dont think travis is running tests. It should be running them so that this gets generated automatically

**Comment by joaogarin** [comment]
I thin because in travis.yml we are specifying the scripts we must also add the ```npm run test``` script there.

**Comment by mrjmd** [comment]
Adding that now, let's see what it does.

**Comment by mrjmd** [comment]
We have this sorted now, and a badge reporting the latest coverage numbers is on the README.
