### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_angular#48]
The 12 recipe default is more than the viewport can display and slows page load. There was some discussion around moving to lazy loading of images but it makes more sense to set the default number lower (3 or 6) and then set up infinite scroll.

This would also mean getting rid of the limit filter, which is one of our less useful filters. This would also likely render the notion of a pager obsolete.

**Comment by mrjmd** [comment]
I went ahead and lowered the default number to 6 in #50. We will still need to implement infinite scrolling.

**Comment by joaogarin** [comment]
I have used https://github.com/orizens/ngx-infinite-scroll before, it worked well for the use case I had. maybe we can give it a try

**Comment by joaogarin** [comment]
fixed on https://github.com/contentacms/contenta_angular/commit/3a15bb924397c3dc7c9e82c2bf47dec32c5a2c86
