### ISSUE TITLE
Double scroll bar?

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_angular#49]
There is some strange behavior going on with the side nav, looks like we are actually getting double scroll bars on our pages. It is kind of hard to notice depending on the monitor but when you scroll all the way up or down you can see two bars.

Not sure what the cause is, probably though it's a sign of some deeper issue.

**Comment by joaogarin** [comment]
Yeah I have noticed this, I will fix this in https://github.com/contentacms/contenta_angular/pull/42

**Comment by mrjmd** [comment]
This appears to be fixed with the merge of #42, closing this out.
