### ISSUE TITLE
Travis pushing every branch

### ISSUE THREAD

**Issue by joaogarin** [contentacms/contenta_angular#52]
Right now our travis setup publishes to https://contenta-angular.firebaseapp.com any branch / PR that passes the travis check.

We should fix it so that only master branch gets published to the site.

**Comment by mrjmd** [comment]
Yeah I noticed this too. It's odd to me that [both](https://medium.com/@jamzi/continuous-everything-with-angular-travis-ci-firebase-and-greenkeeper-6656543bd826) of the [examples](https://houssein.me/continuous-integration-angular-firebase-travisci) of this kind of integration I found use this exact method of deploying, but both would cause this exact same issue.

Anyway I think I have a good idea how to solve this, but will involve another round of CI debugging which is always fun :) Assigning to myself.

**Comment by mrjmd** [comment]
Another [example](https://egghead.io/lessons/setup-automated-deployment-with-angular-travis-and-firebase) that suggests the same method we are using. Very strange, I guess we should write a blog post correcting this approach after we fix it.

**Comment by mrjmd** [comment]
Tested and fixed, this should be working now!

![screen shot 2017-07-21 at 12 03 12 pm](https://user-images.githubusercontent.com/2111857/28478328-c94441fc-6e0c-11e7-8af6-0e7e35a551e2.png)
