### ISSUE TITLE
Issues with the new --build-optimizer flag

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_angular#60]
CLI's new --build-optimizer flag brings our main js bundle size down about 300kb, and the build itself passed fine, but then we see a WSOD and the following error at runtime:

`Uncaught TypeError: Object prototype may only be an Object or null: undefined`

**Comment by mrjmd** [comment]
A little more info here. When I run `ng serve --prod --bo`, we get the runtime error reported above. In an attempt to get better error messages for debugging I tried `ng serve --bo`, which doesn't work because --bo flag requires aot. So then I tried `ng serve --aot --bo`, and the build works fine *and* there are no runtime issues. So this seems to specifically happen with prod mode and build optimizer.

**Comment by mrjmd** [comment]
I went ahead and opened an [issue in the Angular CLI](https://github.com/angular/angular-cli/issues/7190) repo to see if we can get any feedback there.

**Comment by mrjmd** [comment]
Interesting update in the CLI ^ issue, looks like this may be related to something in either contenta_angular_service or angular2-jsonapi services. @mortenson any thoughts?

**Comment by mortenson** [comment]
@mrjmd It looks like this has been fixed per the closing of #7190! Could you try using the `1.3.0-rc.5` release of Angular CLI?

**Comment by mrjmd** [comment]
Oh cool, I will try this out and if so roll a PR later today!

**Comment by mrjmd** [comment]
Looks like this may indeed be fixed, rolled #83.

**Comment by mrjmd** [comment]
This was fixed by `1.3.0-rc.5`, but unfortunately it introduced a breaking change to our service worker, so now this is blocked by [this CLI issue](https://github.com/angular/angular-cli/issues/7280).

**Comment by mrjmd** [comment]
This was merged from #90.
