### ISSUE TITLE
Add function to edit items after user has logged in and has the required permissions

### ISSUE THREAD

**Issue by pvlastaridis** [contentacms/contenta_angular#82]
I think this feature is very important to illustrate how drupal backend can be used as an authenticated rest API. Do you know of any examples on the web showing this possibility.

**Comment by mrjmd** [comment]
Thanks for trying Contenta Angular and opening an issue @pvlastaridis! We agree 100% that this is an important piece, and have an issue open #36 about adding this type of functionality to our project and exploring how others have approached it. Let's move the conversation into that issue, I'm going to close this as a duplicate.

I will actually also be speaking about decoupled editorial interfaces at [DrupalCon Vienna](https://events.drupal.org/vienna2017/sessions/decoupled-drupal-and-editorial-bliss), so making progress on it between now and then would be great!
