### ISSUE TITLE
Switch to Angular Service Worker

### ISSUE THREAD

**Issue by mrjmd** [contentacms/contenta_angular#9]
We should look into moving from using sw-precache to Angular Service Worker. The first obvious benefit of doing so would be the ability to cache our API calls, see here: https://fluin.io/blog/angular-service-worker

**Comment by e0ipso** [comment]
Ouf! Angular looks cooler and cooler the more I read your PRs.

**Comment by joaogarin** [comment]
Yep..This is actually the only one I have used. I thought the cli would use the same since this is the one that comes from the mobile-toolkit 

https://github.com/angular/mobile-toolkit/tree/master/service-worker/worker

**Comment by mrjmd** [comment]
At Google I/O they showcased a PWA using the [ng-pwa-tools](https://www.npmjs.com/package/ng-pwa-tools) library, which goes one step further by automating the generation of the service worker config directly from your app. An example repo using this is [here](https://github.com/alxhub/io17).

**Comment by dawehner** [comment]
I've seen people especially in the create react community having huge
issues with service workers in reality. Does angular have some kind of
special sauce?

**Comment by joaogarin** [comment]
Yes Angular does have a lot of special sauce around service workers, that being said you can still run into somewhat tricky situations. Its an easy opt-out though since the app is not built with any assumptions on service workers for now..And it shouldn't be in my opinion..It should be possible to turn off service worker at any time easily.

**Comment by mrjmd** [comment]
Initial version PR here: https://github.com/contentacms/contenta_angular/pull/39

**Comment by mrjmd** [comment]
This is working well for now. Closing the issue, any specific improvements can be addressed in new issues.
